database:
  driver: "mysql"
  dbname: "db_wlis"
  username: "root"
  password: "root_test"
  host: "localhost"
  port: "3306"

server:
  port: "9005"

gateway:
  ip: "http://10.120.180.124"
  ipIntra: "http://10.1.2.124"
